name: archive

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'  # every 1st of the month

jobs:
  archive:
    runs-on: macOS-latest
    env:
      RTOOT_DEFAULT_TOKEN: ${{ secrets.RTOOT_DEFAULT_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install R packages
        run: Rscript -e 'install.packages(c("rtoot", "DT", "dplyr", "flexdashboard", "rvest"), dependencies = TRUE)'
      - name: Setup config
        run: |
          echo '${{ secrets.RTOOT_TOKEN }}' >> token_bearer.secret
          mkdir -p /Users/runner/Library/Preferences/org.R-project.R/R/rtoot
          Rscript create_token.R
      - name: Create archive
        run: Rscript scripts/get_toots.R
      - name: Commit and push data if changed
        run: |-
          git diff
          git config --global user.email "readme-bot@example.com"
          git config --global user.name "README-bot"
          git add -A
          git commit -m "Updated data" || exit 0
          git push
      - name: Render data table
        run: Rscript -e "rmarkdown::render('index.Rmd')"
      - name: Commit and push if changed
        run: |-
          git diff
          git config --global user.email "readme-bot@example.com"
          git config --global user.name "README-bot"
          git add -A
          git commit -m "Updated content" || exit 0
          git push
